### ISSUE TITLE
Azure Environment to get started - docker tools

### ISSUE THREAD

**Issue by kifjj** [dotnet/eShopOnContainers#103]
Hi,

a bit out of topic, but
I'm new to docker and I want to have the full sln working, hence I tried to use the pre-buil azure vm win2016 with vs2017 however docker tools  requires win 10 pro/entr/edu.
Hence I installed vs 2017 entr on win 10 entr in azure, still problems with docker tools, docker daemon does  n't start. 

Is possible to us an azure vm with docker tools? or a local vm at all?

**Comment by CESARDELATORRE** [comment]
Looks an issue related to "Docker for Windows" installation. Weird, I've installed it in many machines, really quick installation and usually, no issues.
For sure, "Docker for Windows" (from Docker) requires Windows 10 Professional or upper.
About having an Azure VM..., that's not possible because "Docker for Windows" uses Hyper-V for creating the Docker Linux Hox which is a Linux VM running on Hyper-V within you Windows 10.
An Azure VM (like a Windows 10 VM) does not support a [nested Hyper-V VM](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization).
So, nested VM virtualization is not supported in Azure VM, as mentioned here:
https://feedback.azure.com/forums/216843-virtual-machines/suggestions/15879156-allow-nested-virtualization-please
It could be supported in the future. But for now, any development environment that needs Hyper-V or any kind of virtualization, like Docker for Windows, or Android/Windows Emulators, need to run on a local Windows.
About your specific issue, looks like it is specific to your environment, check Docker troubleshooting pages, at Docker: 
https://docs.docker.com/toolbox/faqs/troubleshoot/
