### ISSUE TITLE
SPA web app is not managing images and login properly when running from remote browser

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#112]
When deploying the "prod" environment (using docker-compose.prod.yml with external IPs that you need to change depending on your host machine), the MVC app works OK from a remote browser.

However, the SPA app is not showing the catalog images neither being able to authenticate agains the STS container (IdentityServer4).
An URL like this show no images:
![spa-bug-images-remote](https://cloud.githubusercontent.com/assets/1712635/23785252/99cfa0b0-051b-11e7-9cd4-1eaff37cab80.PNG)

However, if running the same deployment but using the URL http://localhost:5104/catalog then the images show up properly, but the authetication page show an error:
**Sorry, there was an error : unauthorized_client
Request Id: 0HL37FHCF72NO**

**Comment by eiximenis** [comment]
Ok. Both issues (images & login) solved in commit 12ecc78a1818e5a5e644c5b727657dee5c43d165

**Important:** Currently SPA nor our IdentityServer configuration supports running SPA from two different origins.
So, **when running deployed "prod" environment it CAN'T ONLY BE ACCESSED THROUGH EXTERNAL IP**. Using localhost for accessing prod environment will generate issues and it is not supported.

Reason of this is because our current configuration for IdentityServer only allows one supported redirect url for a specific client (the redirect url is the uri where identity server will redirect the user after a successful login. It is set by the client and checked by IdentityServer. Note that IdentityServer supports multiple redirect urls per client, it is just our current configuration that do not).
In the "prod" environment the redirect url of SPA client is set to external IP. When SPA performs login the URL that passes to IdentityServer is the browser origin. So the browser origin must be the same as the external IP, meaning in that only login from external IPs are supported.
@CESARDELATORRE if you want, you can open a new issue to support "multiple redirect urls" on identity server and I'll take a look with lower priority ;-)

Another change I did is to use a environment variable in the docker-compose.prod.yml file to set the external IP. So, there is no need to edit this file to put your correct IP in it.
Now, you **must** set the ESHOP_EXTERNAL_IP environment variable to your external IP. Then you can run docker-compose.
There is no check to ensure the variable is set, but if it is not it won't work. @CESARDELATORRE  please, ensure that this is well documented (i put a comment in the file).

**Comment by CESARDELATORRE** [comment]
I'm not sure I like to use an environment variable (for the the external IP) at the server level used in the docker-compose.prod.yml file to set ALL of the microservices...
It is not only that it requires to set the env var at the server/host level and that will depend on what is your deployment environment (it is not the same if you run Docker for Windows or Mac, a regular Docker Host, or even in the future, a cluster/Swarm, etc.)
Also, chaging a env-var in the setup instructions looks like a more "black box" instructions. Setting it at the docker-compose.prod.yml it helps you to understand how the docker-compose files work.
But most of all, and this is the important reason, I believe that the configuration per each microservice should be 100% autonomous and not sharing any configuration between microservices, at all, coming from the server/host level.
In the dev environment it happens that it is the same IP, but in deployment environments in the future that might change. I think it'd be better to maintain the config at the docker-compose.prod.yml independent per microservice.
I might be wrong but this is my initial gut thinking.. I don't think microservices configuration should be DRY. It should be completely autonomous per microservice, initially at the docker-compose files as the rest of the config we're using.
Thoughts?

**Comment by CESARDELATORRE** [comment]
Confirmed from y side. I think the env-var approach is right for the external IP or DNS NAME across all the microservices under the same docker-compose deployment as they will share the external Docker Host IP or DNS Name or even if it were a cluster or Docker Swarm, the external DNS name would also be the same.

I even went further so in order not to make complex setup instructions with multiple ways to set an environment variable depending on your deplpyment environment (Windows, Mac, Linux, Cluster/Swarm, etc.).
So, the ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the **".env" file** placed at the root folder, which defines it like ESHOP_EXTERNAL_DNS_NAME_OR_IP=192.168.88.248
But, values present in the environment vars at runtime will always override those defined inside the .env file.
This is the commit with this improvement:
https://github.com/dotnet/eShopOnContainers/commit/71987d03f73c30721982d339b63bcdbf4320f1d8

As a reminder, this deployment configuration using the docker-compose.prod.yml file has to be used when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance. Like remote browsers and remote devices.

Closing this ISSUE for now, as I tested it and it is working successfully in my tests.
