### ISSUE TITLE
Unhandled exception when open http://localhost:5104

### ISSUE THREAD

**Issue by ups216** [dotnet/eShopOnContainers#115]
I followed the CLI and Windows based instruction, but the webSPA project is showing error when I open http://localhost:5104, like below 

An unhandled exception occurred while processing the request.

DirectoryNotFoundException: Could not find a part of the path '/app/wwwroot/dist/'.
System.IO.UnixFileSystem+FileSystemEnumerable.OpenDirectory(string fullPath)

While the webmvc and api services are working fine.

**Comment by CESARDELATORRE** [comment]
That means the JavaScript/TypeScript client code was not built correctly before creating the images with docker-compose.
I'd say you had an error about the SPA app when building the bits with docker-compose -f docker-compose.ci.build.yml up
Did you run "npm install" before building the bits with "docker-compose -f docker-compose.ci.build.yml up", as explained in this step in the CLI instructions?
**Get NPM dependencies for the SPA application**
Move to the SPA app folder (cd eShopOnContainers\src\Web\WebSPA) and run npm install

Then you can build the bits with "docker-compose -f docker-compose.ci.build.yml up". While doing so, check that there are no errors in there related to the SPA app.

Take a look to the SPA configuration, too, here:
https://github.com/dotnet/eShopOnContainers/wiki/06.-Setting-the-Web-SPA-application-up

In order to delete the eShopOnContainers images and start fresh you can do it manually with docker rmi per image, or you can run this convenient script that we created:
https://github.com/dotnet/eShopOnContainers/blob/master/cli-windows/delete-images.ps1
Just in case you want to make sure that the Docker images are recreated "for sure".

**Comment by ups216** [comment]
Thanks for quick and detailed reply. I actually did run npm install as per the instruction, but didn't run npm run build:prod. Just tried this again, it worked.
