### ISSUE TITLE
Exception SeedAsync

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/eShopOnContainers#138]
OrderingContextSeed.SeedAsync(app).Wait();

    CatalogContextSeed.SeedAsync(app, loggerFactory)
            .Wait();     

An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code occurred

**Comment by CESARDELATORRE** [comment]
Hi Graham, have you followed the setup procedures, step-by-step here:
**VS2017 enviroment**: https://github.com/dotnet/eShopOnContainers/wiki/02.-Setting-eShopOnContainer-solution-up-in-a-Visual-Studio-2017-environment

**CLI enviroment**: https://github.com/dotnet/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

It yes, can you detail the steps you are taking in order to reproduce that error?
Thanks,

**Comment by jacobpovar** [comment]
I had the same error. 
Changing docker computing resources to recommended values (3 CPUs and 4096 memory) solved the issue.

**Comment by grahamehorner** [comment]
I've increased Docker resources to 4096 with 3 CPUs still have same issue, so increased memory to

**Comment by CESARDELATORRE** [comment]
Hey Graham! Did the memory increase assigned to Docker solve your issue?. Try some more, just in case. It could also depend on how many apps you already started in your dev machine..

**Comment by grahamehorner** [comment]
apologies, had my phone crashed while attempting to posting, yes increasing the memory sorted this issue; I was required to increase the docker memory to 6gb of my 16gb; I'm still working thought some other issues which may/may no be environment related

**Comment by CESARDELATORRE** [comment]
Closing this issue as it was related to Docker memory settings.
