### ISSUE TITLE
Reg: Error While Debugging eShopOnContainers application

### ISSUE THREAD

**Issue by amarendratollplus** [dotnet/eShopOnContainers#1609]
Hello Everyone,

I am using Visual Studio 2019 Version 16.8.5.  I am trying to debug the eShopOnContainers application in my local.  I set  the start up project as docker-compose file and ran the application.  Catalog page with the URL: http://localhost:5100 opened.  On click of the login it triggered the following error:

Error: Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Can some one please let me know how to get the login page on click of the login button. 

Regards,
Amarendra.

**Comment by amarendratollplus** [comment]
Hello All,

 I am completely blocked on this. Can some one please provide your inputs? 

Regards,
Amarendra.

**Comment by sughosneo** [comment]
Hi @amarendratollplus, thank you for reaching out and sorry for the delay in responding.

It could possibly be something wrong with the existing docker containers and images. 
Could you please clean up the existing containers and docker images in your local development environment ? And then press `F5` from Visual Studio to run the solution. If you are using the `Docker Desktop` then you can use **"Clean/Purge data"** feature to remove all the data.

Hope this helps !

**Comment by sughosneo** [comment]
Hi @amarendratollplus , just checking if you had a chance to try out the above mentioned steps. Thank you.

**Comment by amarendratollplus** [comment]
Hello,

The issue is not related to what the steps you had provided. It's related
to the Service URL in docker compose file.  Service URL should be :
host.docker.internal instead of  localhost

Regards,
Amarendra.

**Comment by sughosneo** [comment]
Hi @amarendratollplus, 
Do you see any other error messages on the browser ? It's possible that in the browser dev-tool you may see the error `Refused to load the script 'http://host.docker.internal:5105/lib/jquery/jquery.js'`, but in actual it could be happening for some other reason.  That's why I thought of mentioning the cleaning up steps of the existing containers and images to do a fresh run. 

Did you also try to run the app using `docker compose` ? Do you see the same the issue ? You can do that by using the following steps :

- To do clean up 

```powershell

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker volume rm $(docker volume ls -q)

```

> !IMPORTANT: Above commands will clean up all running containers and it's data in your MacOS/Workstation. So you want to be careful on that.

- To run the app 
- Go to the `/src/` directory

```powershell
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal/window.

```powershell
docker-compose up
```

**Comment by sughosneo** [comment]
Hi @amarendratollplus, did you get a chance to try out the above steps? Thank you.

**Comment by amarendratollplus** [comment]
Hello,

Now it’s working for me, without any issues.

Regards,
Amarendra

**Comment by sughosneo** [comment]
Thank you for the update. I am closing this issue now. Please feel free to reopen, if needed.
