### ISSUE TITLE
[SPA] Cannot build with CLI

### ISSUE THREAD

**Issue by ppopadiyn** [dotnet/eShopOnContainers#162]
Following the steps to setup the solution in a Windows CLI environment, when I run 

```
cd YourPath\eShopOnContainers\
docker-compose -f docker-compose.ci.build.yml up
```
I get the following errors:

```
ci-build_1  | /usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3030: Could not copy the file "/src/src/Web/WebSPA/wwwroot/dist/main.411b08094680fcce978b.bundle.js" because it was not found. [/src/src/Web/WebSPA/WebSPA.csproj]
ci-build_1  | /usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(100,5): error MSB3030: Could not copy the file "/src/src/Web/WebSPA/wwwroot/dist/main.411b08094680fcce978b.bundle.map" because it was not found. [/src/src/Web/WebSPA/WebSPA.csproj]
```
Note that if I run _docker-compose up_ after that the MVC will be run but the SPA app at http://localhost:5104/ won't be accessible.
Just running _npm install_ and then _npm run build:prod_ on the SPA project completes successfully.

**Comment by chlowell** [comment]
This is caused by aspnet/websdk [#143](https://github.com/aspnet/websdk/issues/114). Basically, the publish task copies only files which exist when it begins, therefore excluding the bundled files it generates. There's a workaround in that issue you can apply to the csproj (I've also done it [here](https://github.com/dotnet/eShopOnContainers/blob/eShopOnKubernetes/src/Web/WebSPA/WebSPA.csproj#L81)). That workaround caused problems for me when debugging the containers in VS, so now I copy `wwwroot/dist/main*` to `obj/Docker/publish/wwwroot/dist` myself when I'm building the image.

**Comment by ppopadiyn** [comment]
I tried the workaround but I continued getting the same build errors for the SPA project: "_Could not copy the file....._". So I didn't want to spend more time on this and eventually ran the demo with VisualStudio without any issues.
