### ISSUE TITLE
Build project fails

### ISSUE THREAD

**Issue by ArashFarkish** [dotnet/eShopOnContainers#1653]
I am trying to build the project but it fails. it seems that it is not able to download packages form : https://api.nuget.org
Received an unexpected EOF or 0 bytes from the transport stream.

This is the error however it continues for many other packages. I tried it on two different machines 

 > [build 35/38] RUN dotnet restore "eShopOnContainers-ServicesAndWebApps.sln":
#43 3.909   Determining projects to restore...
#43 32.50   Failed to download package 'xunit.extensibility.core.2.4.1' from 'https://api.nuget.org/v3-flatcontainer/xunit.extensibility.core/2.4.1/xunit.extensibility.core.2.4.1.nupkg'.
#43 32.50    Received an unexpected EOF or 0 bytes from the transport stream.
#43 32.50   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.net.http/index.json'.
#43 32.50   The SSL connection could not be established, see inner exception.
#43 32.50      Received an unexpected EOF or 0 bytes from the transport stream.
#43 33.18   Failed to download package 'Microsoft.Extensions.Configuration.FileExtensions.3.1.11' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.fileextensions/3.1.11/microsoft.extensions.configuration.fileextensions.3.1.11.nupkg'.
#43 33.18    Received an unexpected EOF or 0 bytes from the transport stream.
#43 33.65   Failed to download package 'xunit.extensibility.execution.2.4.1' from 'https://api.nuget.org/v3-flatcontainer/xunit.extensibility.execution/2.4.1/xunit.extensibility.execution.2.4.1.nupkg'.
#43 33.65    Received an unexpected EOF or 0 bytes from the transport stream.
#43 34.62   Failed to download package 'System.Threading.Tasks.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.threading.tasks/4.3.0/system.threading.tasks.4.3.0.nupkg'.

**Comment by sughosneo** [comment]
Hi @ArashFarkish , thank you for reaching out. 

How are you trying to build solution ? Did you take the latest from the `dev` branch ?

**Comment by ArashFarkish** [comment]
Hi @sughosneo, Thanks for the reply. 
I took it yesterday from the Dev branch. 
I am trying to build it using CLI.   Docker-compose build

**Comment by sughosneo** [comment]
Thanks for the update @ArashFarkish. 

I just tested the app and successfully able to build the `dev` branch after taking the latest. 
Is your development machine behind any firewall? Because I see an issue in downloading the Nuget package in the error message. For e.g `Failed to download package 'xunit.extensibility.core.2.4.1`

Could you please try the following steps?

- Pull the latest from the `dev` branch.
- Stop all the running containers `docker stop $(docker ps -aq)`
- Delete all the containers `docker rm $(docker ps -aq)` that are stopped by the previous commands.
- Delete all the volumes by using `docker volume rm $(docker volume ls -q)`
- Better to clean up all old docker images by using `docker rmi -f $(docker images -a -q)`
- Or you could purge all the data by using Docker Desktop UI.
- Then you could go to the `src` directory and build all the images again using `docker-compose build` and then followed by `docker-compose up`

> !IMPORTANT Please note, the above commands will clean up all the docker related instances on that environment. So it's not recommended to run these on any production environment or any other environment where docker instances of any other applications are running.

**Comment by ArashFarkish** [comment]
Hi @sughosneo, 

Thanks for the update. 

I finally was able to find the issue and solve it. It is such a weird issue which I explain. 
Downloading the (nuget) packages was getting timed out due to the internet speed. My internet speed was 5 Mbps which is not that slow but I am assuming that the application was trying to download many of the (nuget) packages simultaneously and they became timed out !
I changed my internet speed to 100 Mbps and the same code complied !
I still see it as a bug in the code and the way it complies as it should be able to accommodate the slow internet connections to compile

**Comment by sughosneo** [comment]
Great ! thank you for the update @ArashFarkish 

Actually, the `eShopOnContainers` application depends on the many such components (For e.g Base/Infra Docker Images) which need to be downloaded from the internet. So that's the reason it requires decent internet connectivity for this application to work. Anyhow, I am glad that you were able to run the application at your end. Please reach out to us if you have any further questions. 

I am closing this issue as of now. Please feel free to reopen it if needed.
