### ISSUE TITLE
Question about api gateway route prefix

### ISSUE THREAD

**Issue by MatheusXavier** [dotnet/eShopOnContainers#1654]
The envoy has the following rules:
- Routes with prefix "**/c/**" forwards to "**/catalog-api/**"
- Routes with prefix "**/o/**" forwards to "**/ordering-api/**" 
- Routes with prefix "**/b/**" forwards to "**/basket-api/**" 

The eShopOnContainers eBook has the following text: "Why consider API Gateways instead of direct client-to-microservice 
communication" and this is one of the reasons:

> **Coupling**: Without the API Gateway pattern, the client apps are coupled to the internal microservices. **The client apps need to know how the multiple areas of the application are decomposed in microservices**. When evolving and refactoring the internal microservices, those actions impact maintenance because they cause breaking changes to the client apps due to the 
direct reference to the internal microservices from the client apps. Client apps need to be updated frequently, making the solution harder to evolve.

So I was thinking, the fact of using a prefix on the route generete a problem: "The client apps need to know how the multiple areas of the application are decomposed in microservices", right? So is it an anti-pattern?

**Comment by sughosneo** [comment]
Hi @MatheusXavier, thank you for reaching out. 

As mentioned in the [Why consider API Gateways instead of direct client-to-microservice communication](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern#why-consider-api-gateways-instead-of-direct-client-to-microservice-communication) section,  one of the issues for not using API Gateway pattern with the `microservices architecture` is that the client needs to know all the details of each microservice and so that it can make the necessary calls to individual microservie and consolidate the result whenever it's needed. In the `eShopOnContainers` reference application, the `Envoy` Service proxy has been used as API Gateway that acts as a layer between your client and individual microservice in the application. 

With the `route_config` in place in the `Envoy` configuration, each incoming request from the client gets diverted based on the matching prefix. Even it can be diverted to the aggregator if necessary. For e.g : `shoppingagg` . This gives us the flexibility to decouple the client from each microservices. So if necessary, we can modify the catalog or any other microservice that won't have any impact on the client-side, as long as we are keeping the configuration updated in the `envoy.yaml`. Prefix routes are denotation of each microservice it doesn't have any physical existence. You can very well replace these routes and have these pointed to any microservice you want without even informing the client.  So as you could see, this is not an antipattern rather very helpful in the large microservices architecture. 


Hope this helps !

**Comment by MatheusXavier** [comment]
Yes, it helped me a lot. Thanks!
