### ISSUE TITLE
Slow way to update prices in basket?

### ISSUE THREAD

**Issue by worthy7** [dotnet/eShopOnContainers#1668]
https://github.com/dotnet-architecture/eShopOnContainers/blob/d0cd2830a864a8b975341b02b93a0887a3908c04/src/Services/Basket/Basket.API/IntegrationEvents/EventHandling/ProductPriceChangedIntegrationEventHandler.cs#L33

This seems like a very inefficient way to update prices in the baskets of users, I doubt this would ever be done like this in a real app, can we get some insight on how this kind of behavior _would_ actually be managed?
I was thinking to separate our the basket items into their own aggregate root each? Separate index?

**Comment by sughosneo** [comment]
Hi @worthy7, thank you for reaching out. 

Please note that the `eShopOnContainers` is the reference application that focuses on the architectural pattern rather on specific business logic. For understanding more about `ProductPriceChangedIntegrationEvent` you can read [Subscribing to events](https://docs.microsoft.com/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events)
In your production application, implementation will depend on the context of your actual business logic and what you need to achieve. So you can certainly modify/update it as per your requirement.

I am not sure how it's going to be useful more `if you have separate basket items into their own aggregate root each` because this is already acting as a child entity for the https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Basket/Basket.API/Model/CustomerBasket.cs where each basket has its own index/id for each instance. Could you please elaborate on that more?

**Comment by sughosneo** [comment]
Hi @worthy7 , just checking if you were able to make further progress on this topic. Thank you.

**Comment by worthy7** [comment]
Hi sorry for not responding.

My understanding is that when a product is placed into a basket, it also has a copy of the price at that time.

So imagine the scenario where a customer puts item A into their baskey.
Then the store managers change the price of items A.
How does the system now update the price of all Item A's that are in all pending shopping carts?
I believe the code I reference is that.

Is looping over every single customer in the entire system, pulling their card out, checking its contents and updating it really efficient? It seems unrealistic. So I was asking if this is really the way this kind of functionality would be handled.

The only solution I can see is a deep query instead of the shopping carts to find all cards with the item in it first. Ignore what I said about the items becoming an aggregate.

**Comment by sughosneo** [comment]
Thank you @worthy7, for providing more details. 

Yes, you are right. It has a copy of the price in the `BasketItem` model.`ProductPriceChangedIntegrationEvent` gets processed in the background. Based on that, a user can expect to see a notification in the Cart UI. Suppose this implementation doesn't suit well for your actual business scenario. In that case, you can think of implementing *"Query the price change of the cart items during the order submission phase again. And let the user know the price difference, if any"*. The user can then cancel the order or proceed with the new change.

**Comment by worthy7** [comment]
Ah I see, as a confirmation step. Got it thanks.

**Comment by sughosneo** [comment]
I am closing this issue as of now. Please feel free to reopen if needed. Thank you.
