### ISSUE TITLE
Cannot remove from cart?

### ISSUE THREAD

**Issue by VictorZakharov** [dotnet/eShopOnContainers#1692]
It seems there is no way to remove items from cart once added.
I tried setting 0 items and update - but then it fails UI validation.

![image](https://user-images.githubusercontent.com/8978766/120854469-378ae280-c54b-11eb-9bab-9d669e8cbe93.png)

**Comment by sughosneo** [comment]
Hi @VictorZakharov, thank you for reaching out and your feedback.

Yes, you are right. As of now, we don't have any option to remove the item from the cart. `eShopOnContainers` is a reference application that focuses more on the architectural pattern than functionality. That's why this feature was never implemented.
But if you or someone from the community wish to implement this feature and submit a PR, we'll be happy to review and accept the changes. 

Hope this helps !

**Comment by sughosneo** [comment]
Now, WebSPA visual design and styles have been updated and you have an option to remove the items from the cart. For more details, please take the latest from the `dev` branch.

![image](https://user-images.githubusercontent.com/13281246/123091130-99ea4b00-d446-11eb-861e-e02f4614c6ae.png)

**Comment by VictorZakharov** [comment]
So there is still no way to remove from cart from within the cart interface? @sughosneo

**Comment by sughosneo** [comment]
This feature is only available now in the `WebSPA`. Thanks.

**Comment by sughosneo** [comment]
As the question has been answered already, I am closing this issue as of now. Please feel free to reopen, if needed. Thank you.
