### ISSUE TITLE
What is the reasoning behind using two different namespaces in Services/Ordering? 

### ISSUE THREAD

**Issue by mdhthahmd** [dotnet/eShopOnContainers#1726]
hello,
this maybe trivial but here goes,
i am trying to understand and refer this project, currently i am looking into API of Ordering,
i have noticed there are two namespaces used with in application part of the Ordering.API

for example in Application Commands
`CancelOrderCommand` is under `Ordering.API.Application.Commands`,
`CreateOrderCommand` is under `Microsoft.eShopOnContainers.Services.Ordering.API.Application.Commands`

my question is what is the purpose of using two different namespaces here?

**Comment by sughosneo** [comment]
Hi @mdhthahmd, thank you for pointing it out. 

Actually, there is no specific reason because which the namespaces are different. Ideally, it should start with the `Microsoft.eShopOnContainers.Services.` prefix for individual service. We can update the namespaces across all the projects. Would you like to submit a PR? Will be happy to review and merge the changes in.

**Comment by sughosneo** [comment]
Hi @mdhthahmd, as the original question has already been answered, I am archiving this issue as of now. Please feel free to reopen if needed. Thank you.
