### ISSUE TITLE
[Question] How to deal with integration events and horizontal scaling (ensure order)

### ISSUE THREAD

**Issue by andiexer** [dotnet/eShopOnContainers#1765]
Hi folks!
I'm curious how the following scenario should/could work:

If you scale the basket api to 2 pods (if you run it on k8s) how would you ensure, that the `priceChangedEvents` occur in the right order? 

Example Messages: `priceChangedEvent:ProductA:5` --> `priceChangedEvent:ProductA:10`

If basket pod 1 takes the first event, basket pod 2 the second event and the basked pod 2 is faster than the first one, the data would be wrong, because both write into the same redis db. The current basket code is not aware to ensure the correct event order I think.

what's the best solution here? leader election and only one consumer is actively working on the queue or something like partitioning?

if this question is duplicated i'm sorry 😄 , didn't found anything

regards,
Andi

**Comment by sughosneo** [comment]
Hi @andiexer, thank you for reaching out. Interesting question :thumbsup:

I would probably think of including a timestamp in each event. Something as per below:

```text
{
aggregated_id: #1234-2efd-,
event_created_timestamp: t2,
val: 10
event_name: ProductPriceChanged
}

{
aggregated_id: #1234-2efd-,
event_created_timestamp: t1,
val: 5
event_name: ProductPriceChanged
}
.....
```

And then in each microservice side, you will keep track of every incoming event that a microservice needs to process. And if subscribed microservice receives an event with a timestamp that is greater than previously-stored latest that point in time. It'll have an option to discard the second event or take any further action based on your business scenario. 

For e.g : Let's consider the above events, where two events got emitted by other microservice for the different subscribers to consume and act. Where the `t1`/`t2` denoted the timestamps when events were actually created and t2>t1. And let's assume, for some reason, the event with the `t2` timestamp gets published and delivered first to other microservices before `t1` by virtue of the FIFO delivery nature of the service bus. And if you are persisting the events before processing it directly (`something like Inbox pattern`), you can check if the next event (`t1` in this scenario) has a greater timestamp than the latest. Based on that, you can take action to process or discard based on your business scenario. 

I am sure there could be other interesting solutions to it as well :blush: So let's hear from others too.

**Comment by andiexer** [comment]
Hey @sughosneo 
Yeah, i also thought about something like that (except the inbox pattern). But let's imagine this:

![image](https://user-images.githubusercontent.com/17616887/135616650-38ef2a1f-5cf9-4bdf-bb7f-63d9f3fa2afd.png)

3 Instances from the same service, writing against the same data store (like the basket api). 3 events will be raised in the correct order: `Product Created` < `Product Updated` < `Product Deleted`

all 3 instances will listen on the same queue in kinda `worker queue` config or however we should call this. Means: they do some kind of round robin, the messages will be distributed. 

now this happens in this order, because no one knows about the others: 
POD3 `event 3`:  will be a little confused, because there's nothing here to delete
POD1 `event 1`:  ok, so let's add the product
POD2 `event 2`: will think: nice, `t2 > t1` so let's update the product

So we will have a product where no product should be, right? 

I also came up with something like: everyone gets everything, they have to deal with duplicates and wrong versions like: `current event version (or t) > db version (or t)`

or

we spawn a `hosted service` which listens to the queue, but only one of the three pods is actively listening on the queue until the pod is deleted and another one has to take over (leader election)

I know, this will probably never happen. Maybe I'm overthinking this really hard?!

**Comment by sughosneo** [comment]
From your example point of view, the ideal scenario is - "if the events get generated from microservice `A` in the correct order, gets published in service bus in that right sequence and also get recevied in microservice `B` in the same order". For example, let's understand that the below events are created in the following manner.

t1 : `ProductCreated`
t2 : `ProductUpdated`
t3 : `ProductDeleted`

Now let's assume because of some failures either in the microservice `A` side or in the service bus, `ProductDeleted` event with `t3` timestamp reaches the microservice `B` before the event `ProductUpdate` with `t2` timestamp. If you are keeping track of all the previously processed events with Ids and timestamps at the side of microservice `B`, you can take necessary actions on that. 

> NOTE : But you need to make sure processing the events and persisting the processed event details in the database should be performed under the same transaction, otherwise you may end up processing the same events again and again.

Now in microservice `B`, if you have more than one pod to process the events in parallel, I don't see any problem in there. Because the same code snippets are in all the pods. So, before processing any of the events, it would always check with the database to see if it has already been processed or if it has an older timestamp than the previously processed one. And then your code will be able to take necessary action on that. 

But I totally agree with you on the "overthinking part" 😄 this may sound easy but may get complex very quickly as it has many corner scenarios that you may have to handle in your actual implementation.

**Comment by sughosneo** [comment]
Considering the original question has been answered, I am closing this issue as of now. Please feel free to reopen if needed. Thank you.

**Comment by MatheusXavier** [comment]
Considering a scenario where I have `microservice A` producing an integration event where `microservices B` and `C` are subscribed and `microservices B and C` are running in multiple pods, what is the best approach?

1. Having a subscription manager that allows only one subscription per microservice, so even running microservice B in three pods only one will subscribe to this event like @andiexer said
2. Have all instances of microservices subscribing to the event but saving the event being processed in the database and when the instance starts processing it saves in the database preventing other instances from processing the same event like @sughosneo said
