### ISSUE TITLE
polly under RabbitMQ

### ISSUE THREAD

**Issue by menuconz** [dotnet/eShopOnContainers#1807]
Why Polly is referenced under RabbitMQ. How to use Polly if I remove RabbitMQ and use Azure service bus.
Do I need to add  Azure service bus conectionstring in env file.

**Comment by onurkanbakirci** [comment]
Hi @menuconz . From the Polly offical documentation;
_Polly is a .NET resilience and transient-fault-handling library that allows developers to express policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, Rate-limiting and Fallback in a fluent and thread-safe manner.`_

In the RabbitMQ project, Polly is used to define RabbitMQ connection procedures. For example, when trying to connect RabbitMQ, If there will be error in first connection attempt, 
- How many times try to connect RabbitMQ, 
- What is the sleep duration between these retries,
- Function will called each retry etc.

So if you want to use Azure service bus there will be same logic. Because its actually not related about RabbitMQ or Azure Service Bus. Polly defines procedures when trying to do something.

**Comment by erjain** [comment]
Hi @menuconz, thanks for posting your query. Thanks @onurkanbakirci for your response to the above issue. @menuconz you can refer to the link https://azure.microsoft.com/en-us/blog/using-the-retry-pattern-to-make-your-cloud-application-more-resilient/ for more information. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
