### ISSUE TITLE
JQuery Datatables

### ISSUE THREAD

**Issue by josephwambura** [dotnet/eShopOnContainers#1815]
Requesting a feature: Can we use server-side processing JQuery Datatables to list catalog?

**Comment by erjain** [comment]
Hi @josephwambura, Thanks for posting here, if you can share any sample, we can review it and have it in our wiki documentation as a separate sample demonstration of the server-side processing JQuery Datatables. I am closing this issue since this is not an issue, however, feel free to reopen or continue the conversation.
