### ISSUE TITLE
Links not working 

### ISSUE THREAD

**Issue by ragzkotalwar** [dotnet/eShopOnContainers#1832]
Deployment related links are not working ....

https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploying-Azure-resources#azure-resources-used-by-the-services 

Can the solution be executed on local machine without docker?

**Comment by VaishaliRaval** [comment]
Thank you @ragzkotalwar for reporting this. The broken link issue is fixed.

Since this is a reference application based on docker containers it is recommended to use docker. You can also run this application with Kubernetes locally and follow the steps mentioned in this [link](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)

I am closing this issue, however, feel free to continue the conversation or reopen if you are looking for more help
