### ISSUE TITLE
Navigating to <url>:5104 (webspa app), does not load with error  'The antiforgery token could not be decrypted.'

### ISSUE THREAD

**Issue by nkolchakov** [dotnet/eShopOnContainers#1890]
I'm running the app from Docker-Compose debugger inside Visual Studio. When I'm trying to navigate and use the `webspa` on port 5104, the loading hangs and eventually timeouts while `webspa`'s container  throws `AntiforgeryValidationException`

webspa's container log:
```
[13:14:35 ERR] An exception was thrown while deserializing the token.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.

 ---> System.Security.Cryptography.CryptographicException: The key {780770a2-2bf4-45d6-af93-27670034b857} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning

   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)

   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)

   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)

   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

```
Running containers:
![image](https://user-images.githubusercontent.com/6750195/162207646-a458aad1-5bd7-4f64-b1ce-7f90c64ec0b3.png)

I also followed the [steps](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#webspa-project-doesnt-come-up-on-debug-mode-in-visual-studio-2019), for debugging `webspa`

**Comment by nkolchakov** [comment]
10 minutes later .. while writing the issue it fixed by itself and now it's responsive on port `5104` ..

**Comment by nkolchakov** [comment]
Reproduced it again, a few minutes later it works fine. Before closing the issue, does anyone have an idea why it needs some solid 7-10 minutes, to start working ?

**Comment by erjain** [comment]
Hi @nkolchakov, Thanks for posting your query. Since application depends on many components - base images, and need to build each microservice initially, and while running the application the first time, it requires a decent amount of time. WebSPA has to build the packages too and wait for all other microservices to get up and running. 
Maybe you can change the configuration in visual studio, rather than debugging every microservice each time you can run without debugging some of the microservices. It will take lesser time to start the application. Or you can do a “docker-compose Build” just once (it’ll take its time) and then whenever you want to just run it, just do a “Docker-compose up” and since the images will be built, it’ll take much less time. I am closing this issue as of now, please feel free in case you have more queries.
