### ISSUE TITLE
tried to upgrade nuget pacakges. so many error on serilog, identity server 4

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/eShopOnContainers#1920]
tried to upgrade nuget pacakges. so many error on serilog, identity server 4

**Comment by KamranShahid** [comment]
able to correct error in serilog by providing null parameter in WriteTo.Http

**Comment by erjain** [comment]
Hi @KamranShahid, Thanks for posting your query. Are you looking for further help?

**Comment by KamranShahid** [comment]
Nop,
Have done one cycle with serilog updates successfully (with requred code changes). in free time will try to update identity server as well. There was one fork branch which has update but bit old. try to use that one along with my upgraded one

**Comment by erjain** [comment]
Thanks for your contribution @KamranShahid, would you like to share the link for your branch so that it can help community members. In the future, if someone wants to refer to that he can do so. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.

**Comment by KamranShahid** [comment]
Hi erjain,
I was just playing with upgrade on local copied code and haven't made any branch. i have upgraded all the packages other then identityserver4 and compiled the code in it
