### ISSUE TITLE
Question on docker-compose up command disk space

### ISSUE THREAD

**Issue by dogaanismail** [dotnet/eShopOnContainers#1925]
Hello,

I would like to ask a question about using docker-compose up command. 

When I run **docker-compose up** command, there is no space on the device where the command is being executed. My question is that why does it take up so much space? I do not have perfect knowledge of Docker containerization.

**Comment by erjain** [comment]
Hello @dogaanismail, Thanks for posting your query. Whenever you run `docker-compose up` it will build, creates the image, starts, and attaches to containers for a service. Sometimes due to less space or unused or old volumes or images, space is unavailable. You should remove any unused volumes or images before running this command. For more information on Docker, sharing a link: https://docs.docker.com/engine/reference/commandline/compose_up/. 

Also in case you want to remove images or volumes, try these commands: `docker volume rm $(docker volume ls -qf dangling=true)`
`docker rmi {image-name}`
`docker image rm -f $( docker images -q  --filter "since=<imagename or ID>")`

I am closing this issue, please feel free to reopen it in case you have further questions.
