### ISSUE TITLE
[Ordering] BeginTransactionAsync null check.

### ISSUE THREAD

**Issue by LangSensei** [dotnet/eShopOnContainers#1931]
https://github.com/dotnet-architecture/eShopOnContainers/blob/37474024fa538f19a2d47db38ca1fa9b3d5d617b/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs#L58-L65

https://github.com/dotnet-architecture/eShopOnContainers/blob/37474024fa538f19a2d47db38ca1fa9b3d5d617b/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs#L38-L53

Why is BeginTransactionAsync missing null check? Shouldn't we throw an exception when the current transaction is occupied?

**Comment by erjain** [comment]
Hi @LangSensei, thanks for posting here. The below line is used to check if the _currentTransaction is null or not:

https://github.com/dotnet-architecture/eShopOnContainers/blob/37474024fa538f19a2d47db38ca1fa9b3d5d617b/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs#L58-L61

If null, then only it will set the value using the below statement:
 https://github.com/dotnet-architecture/eShopOnContainers/blob/37474024fa538f19a2d47db38ca1fa9b3d5d617b/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs#L62-L65

I am closing this issue since it's not an issue. However, please feel to continue the conversation here.
