### ISSUE TITLE
hot code replace

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/eShopOnContainers#1969]
hi
   1. how to do hot code replace? dotnet run watch?
   2. how to browse the mongDB/mysql/redis data?
thanks

**Comment by erjain** [comment]
Hi @quantrpeter, thanks for posting your query. 
There are multiple ways of doing hot reloading. 
From Visual Studio, after running your application in debug mode with F5, you can configure Hot Reload by selecting Settings from the Hot Reload drop-down button. Or please visit this link: https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022 for detailed knowledge on how to enable hot reloading via visual studio 2022. 
From the command prompt, you can also run the command `dotnet run watch`, or you can visit the link https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch for detailed knowledge on dotnet watch. 
In the current eShop application, we are not using mongoDB/mysql, for Redis you can visit the section "Viewing data in with Redis Insight" on page https://redis.io/docs/stack/get-started/tutorials/stack-dotnet/. I hope it helps. I am closing it since this is not an issue, however, feel free to post here in case of any further queries.
