### ISSUE TITLE
How to create the stack in Portainer?

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShopOnContainers#1971]
I used docker-compose.yml but some services could not be started.

![image](https://user-images.githubusercontent.com/21274590/189030872-d86da264-675f-4ed4-95b4-15594fd7210c.png)

Is it because of the environment variable?

![image](https://user-images.githubusercontent.com/21274590/189030954-71e8a92d-afda-4527-b8f2-81457551f851.png)

**Comment by erjain** [comment]
Hi @ngaisteve1, I have checked the application and it is working fine for me. We are not able to test it on Portainer, this is great that you are trying on it. Due to bandwidth and maintainability, we are keeping it a low priority. Still, if anyone in the community wants to give this a try and capture the steps as a blog/article, we will be happy to link it to the wiki. I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
