### ISSUE TITLE
User Workload for Load Testing

### ISSUE THREAD

**Issue by elibakshi** [dotnet/eShopOnContainers#1996]
I noticed that the [load testing](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Load-testing) section within the Wiki contains alternative tools to use with eShopOnContainers.

I am wondering if there is any existing user workload/user trace for eShopOnContainers to use as a reference when load testing? It would be great to have!

I really appreciate any input. Cheers!

**Comment by erjain** [comment]
Hi @elibakshi, thanks for posting here. Since load testing is deprecated in Visual Studio, there is no such user trace available for eShopOnContainers. However, you can check the link for loadtesting alternatives: https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/#load-testing-alternatives. I am closing this issue as of now, however, you can continue your conversation here.

**Comment by elibakshi** [comment]
Hello @erjain, I appreciate your response, and thank you for the alternative tools!

I am actually planning on using Apache JMeter for load testing already. I am more concerned if there is an existing workload/user trace that reflects how users would typically interact with a service like eShopOnContainers, to then plug into something like Apache JMeter.

This is so that I can accurately simulate load based on real user requests/scenarios rather than me making up my own.

Would perhaps the deprecated load testing in Visual Studio have some sort of old user trace file or user workflow that I could use?
