### ISSUE TITLE
Potential Race Condition?

### ISSUE THREAD

**Issue by WadeVillines** [dotnet/eShopOnContainers#2001]
I'm curious if there is a race condition when adjusting stock in the Catalog microservice.

- In the Catalog service, the _OrderStatusChangedToAwaitingValidationIntegrationEventHandler_ will check if there are enough items in stock before publishing a _OrderStockConfirmedIntegrationEvent_. 
- Then, the Payment service will process payment for the order.
- Finally, the Catalog service will decrement the inventory.

What happens if two orders are received simultaneously, and they both want all of the available stock? Inventory isn't updated until after payment is processed for an order, so the Catalog service could mistakenly think that there is enough inventory for both orders, because inventory hasn't been updated for the first order yet.

Have I analyzed this correctly? Would this be an actual issue in a production environment? Or is this simply outside the scope of this demo application?

**Comment by erjain** [comment]
Hi @wadeVillines, thanks for sharing your query here. This problem is a real-world problem, however, this application is not production ready, the purpose of this sample application is just to provide a sample application showing how to use microservices and Docker containers plus showing multiple clients(WebMVC, WebSPA, etc). 
For concurrent scenarios, I prefer you can also check our docs link: https://learn.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/state-management. 
I hope it helps you. I am closing this issue as of now, please feel free to post here in case of more queries.
