### ISSUE TITLE
eShopOnContainers - migrate to .NET 7

### ISSUE THREAD

**Issue by erjain** [dotnet/eShopOnContainers#2010]
- [x] Implement Duende IdentityServer 6.2.0 to replace IdentityServer4 3.1

- [x] Updates   all Dockerfile for individual projects to use the latest   mcr.microsoft.com/dotnet/sdk:7.0 and runtime   mcr.microsoft.com/dotnet/runtime:7.0

- [x] update each   Microsoft.AspNetCore.*, Microsoft.EntityFrameworkCore.*,   Microsoft.Extensions.*, and System.Net.Http.Json package reference's Version   attribute to 7.0.0 or later

- [x] Update GitHub   Action Workflow
- [x] Update   Services\Basket\Basket.API\Basket.API.csproj
- [x] Update   Services\Catalog\Catalog.API\Catalog.API.csproj
- [x] Update   Services\Ordering\Ordering.API\Ordering.API.csproj
- [x] Update   Services\Ordering\Ordering.Domain\Ordering.Domain.csproj

- [x] Update   Web\WebMVC\WebMVC.csproj
- [x] Update   Services\Ordering\Ordering.Infrastructure\Ordering.Infrastructure.csproj
- [x] Update   Services\Identity\Identity.API\Identity.API.csproj
- [x] Update   Web\WebSPA\WebSPA.csproj
- [x] Update   BuildingBlocks\EventBus\EventBus\EventBus.csproj
- [x] Update   BuildingBlocks\EventBus\EventBusRabbitMQ\EventBusRabbitMQ.csproj
- [x] Update   BuildingBlocks\EventBus\IntegrationEventLogEF\IntegrationEventLogEF.csproj
- [x] Update   Web\WebStatus\WebStatus.csproj
- [x] Update   BuildingBlocks\EventBus\EventBusServiceBus\EventBusServiceBus.csproj
- [x] Update   BuildingBlocks\WebHostCustomization\WebHost.Customization\WebHost.Customization.csproj
- [x] Update   Web.Bff.Shopping
- [x] Update   ApiGateways\Web.Bff.Shopping\aggregator\Web.Shopping.HttpAggregator.csproj
- [x] Update   Services\Ordering\Ordering.SignalrHub\Ordering.SignalrHub.csproj
- [x] Update   Services\Basket\Basket.UnitTests\Basket.UnitTests.csproj
- [x] Update   Services\Catalog\Catalog.UnitTests\Catalog.UnitTests.csproj
- [x] Update   Services\Basket\Basket.FunctionalTests\Basket.FunctionalTests.csproj
- [x] Update   Services\Ordering\Ordering.UnitTests\Ordering.UnitTests.csproj
- [x] Update   Services\Catalog\Catalog.FunctionalTests\Catalog.FunctionalTests.csproj
- [x] Update   Services\Ordering\Ordering.FunctionalTests\Ordering.FunctionalTests.csproj
- [x] Update   Tests\Services\Application.FunctionalTests\Application.FunctionalTests.csproj
- [x] Update   Services\Payment\Payment.API\Payment.API.csproj
- [x] Update   Services\Webhooks\Webhooks.API\Webhooks.API.csproj
- [x] Update   Web\WebhookClient\WebhookClient.csproj
- [x] Update   BuildingBlocks\Devspaces.Support\Devspaces.Support.csproj
- [x] Update   Services\Ordering\Ordering.BackgroundTasks\Ordering.BackgroundTasks.csproj
- [x] Update   ApiGateways\Mobile.Bff.Shopping\aggregator\Mobile.Shopping.HttpAggregator.csproj
- [x] Update   BuildingBlocks\EventBus\EventBus.Tests\EventBus.Tests.csproj

**Comment by Sensis04** [comment]
Hi everyone, hi @erjain,

I was not sure if I should open a new issue or not - I hope this is fine. 

I'm not able to start the Net7 version of the application for debug via VS 2022 while a simple `docker compose && docker up` via CLI works as expected. There are only minor modification and updates to the packages. With the default Docker files via VS 2022 the error is

`System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request. Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.`

Updating the SPA dockerfile for development and adding

`RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_17.x | bash -
RUN apt-get -y install nodejs
RUN npm install
RUN npm -v`

results in `failed to solve: executor failed running [bin/sh -c npm install]: exit code: 254`.

Does anybody have ideas how to resolve these errors for the updated version? I have tried deleting, rebuilt all images without caches, and switched between development and production for the SPA application.

**Comment by Broderick890** [comment]
Because Duende IdentityServer is charged, it is not recommended to use it.Use openiddic instead.

**Comment by erjain** [comment]
Since the original implementation was with IdentityServer4, moving to Duende, which is a kind of IS4 vNext was more straightforward, however, read through the [documentation](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio) on the many options available for developers.
