### ISSUE TITLE
Error requesting catalog products, please try later on

### ISSUE THREAD

**Issue by Jaswir** [dotnet/eShopOnContainers#2074]
When I try this exercise : https://learn.microsoft.com/en-us/training/modules/microservices-resiliency-aspnet-core/2-environment-setup

And run the Web SPA App it fails.  Can't do the exercise because of that :(

![Error_Exercise](https://user-images.githubusercontent.com/15957528/228008567-2b367312-bf0a-486e-a9f0-3be2c3dabba7.png)

![image](https://user-images.githubusercontent.com/15957528/228008870-757e20ad-bedb-4ebe-a97b-7b7565168fef.png)

![image](https://user-images.githubusercontent.com/15957528/228008628-c95cf65f-07d2-4117-8df1-12cc6786f188.png)

**Comment by erjain** [comment]
Hi @Jaswir, thanks for sharing your query. I am transferring this issue to the correct repo: https://github.com/MicrosoftDocs/mslearn-aspnet-core. We will check your problem and get back to you with our findings. I am closing this issue here since a duplicate is opened in mslearn-aspnet-core: https://github.com/MicrosoftDocs/mslearn-aspnet-core/issues/177
