### ISSUE TITLE
Cannot build SPA app from Linux build-container if SPA client content was prepared from the Windows environment 

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/eShopOnContainers#79]
When trying to build the solution from the build-container, when building the SPA, if the SPA app was previously prepared with "nmp install" or "npm build" from the Windows environment, you get errors saying you'd need to run "npm rebuild node-sass" first so it is compliant with Linux environment.

**Comment by eiximenis** [comment]
Just a comment on this...
Mixing environments could lead to some unwanted situations, like this :)

Another one (this is the opposite) is that:

1. You clone the repo.
2. Do the build using docker-compose.ci.build.yml (or docker-compose.local.build.yml) and you'll end with node_modules folder (in the SPA app) filled with the modules of Linux, which are the same modules that windows but without the .cmd file in the node_modules/.bin folder. 
3. Later you try to do a build from windows CLI: SPA will crash because some modules (i. e. rimraf) are not found (because their .cmd is missing in node_modules folder).

A way to deal with this issue is remove node_modules folder and do another npm install to reinstall the packages under windows environment. 
Note: After you did a npm install under windows, docker-based builds still work, so it's better to do once at the beginning and forget about it :)

Not sure if any other issues could appear by mixing linux&windows based builds.

**Comment by CESARDELATORRE** [comment]
OK, it is already documented like that, so closing this issue.
